### PR TITLE
Corrected use of 'this' in a static method

### PR DESCRIPTION
**Pull request by framespaces-dev**
Hi Kevin, a minor fix for you! Best wishes

### CODE REVIEW

**Comment by brandonpayton** [comment]
That was my mistake in a past PR. Thanks for fixing it.

**Comment by thelonious** [comment]
@brandonpayton I guess this doesn't break your original intention for allowing subclasses to work as expected? I guess in this case, your subclass would have to add its own `fromPoints` static method?

**Comment by brandonpayton** [comment]
Yeah, a subclass would have to add the method to its constructor.

If you wanted to make that easier by assignment, you could change [this return statement](https://github.com/thelonious/kld-affine/pull/8/commits/096fdda2b2764717226ad2ebf97ef3e652b14131#diff-9b7df777645bbe74eb0c8e0f08e70db2L43) to:

```
Vector2D.fromPoints = function(p1, p2) {
    return new this(
```

Then you could do the following and have it work as expected:

```
VectorSubclass.fromPoints = Vector2D.fromPoints;
```

There may be better ways to deal with "static" methods like this, but if so, I'm not aware of them.

**Comment by thelonious** [comment]
I need to setup Babel. What I think we'd want here works in ES6:

``` JS
class Vector {
    constructor(x, y) {
        this.x = x;
        this.y = y;
    }

    toString() {
        return this.constructor.name + ".prototype.toString()";
    }

    static fromPoints(p1, p2) {
        return new this(p2.x - p1.x, p2.y - p1.y);
    }
}

class MyVector extends Vector {

}

let p1 = { x: 10, y: 20 };
let p2 = { x: 30, y: 50 };

let v = new Vector(10, 20);
let m = new MyVector(20, 30);
let m2 = MyVector.fromPoints(p1, p2);

console.log("v.toString() = %s", v.toString());
console.log("m.toString() = %s", m.toString());
console.log("m2.toString() = %s", m2.toString());
```

This outputs:

```
v.toString() = Vector.prototype.toString()
m.toString() = MyVector.prototype.toString()
m2.toString() = MyVector.prototype.toString()
```

**Comment by brandonpayton** [comment]
That's a good idea.

I've only used Babel, but some people I respect have been using [Bublé](https://buble.surge.sh/guide/#what-is-buble) because it has cleaner output. I wondered how the transpilers were implementing inherited static methods and investigated. In case you're interested, here's what I found.

Bublé assigns to `__proto__` which is a bit strange to me, but it is a succinct approach.

Input:

``` javascript
class BaseClass {
  static someStaticMethod() {
    console.log('someStaticMethod');
  }
}

class ChildClass extends BaseClass {}

ChildClass.someStaticMethod();
```

Babel output:

``` javascript
'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var BaseClass = function () {
  function BaseClass() {
    _classCallCheck(this, BaseClass);
  }

  _createClass(BaseClass, null, [{
    key: 'someStaticMethod',
    value: function someStaticMethod() {
      console.log('someStaticMethod');
    }
  }]);

  return BaseClass;
}();

var ChildClass = function (_BaseClass) {
  _inherits(ChildClass, _BaseClass);

  function ChildClass() {
    _classCallCheck(this, ChildClass);

    return _possibleConstructorReturn(this, Object.getPrototypeOf(ChildClass).apply(this, arguments));
  }

  return ChildClass;
}(BaseClass);

ChildClass.someStaticMethod();
```

Bublé output:

``` javascript
var BaseClass = function BaseClass () {};

BaseClass.someStaticMethod = function someStaticMethod () {
  console.log('someStaticMethod');
};

var ChildClass = (function (BaseClass) {
  function ChildClass () {
    BaseClass.apply(this, arguments);
  }if ( BaseClass ) ChildClass.__proto__ = BaseClass;
  ChildClass.prototype = Object.create( BaseClass && BaseClass.prototype );
  ChildClass.prototype.constructor = ChildClass;



  return ChildClass;
}(BaseClass));

ChildClass.someStaticMethod();
```

**Comment by thelonious** [comment]
@brandonpayton Nice! Thanks for the info.

@framespaces-dev I'm going to be afk all day today, so I may not get back to this until tomorrow.

**Comment by framespaces-dev** [comment]
Thanks @thelonious and @brandonpayton. No rush from my side.

**Comment by lysz210** [comment]
How about rewriting the lib in [Typescript](https://www.typescriptlang.org/), it's a great alternative to write js code and it compiles in many esX version.

**Comment by thelonious** [comment]
@framespaces-dev OK, I've merged your change. Thanks for sending that in.

**Comment by thelonious** [comment]
@lysz210 Yes, Typescript looks really nice. Now, I'm speaking out of total ignorance of Typescript's output, but typically the generated code from languages on top of JS don't look very good and hence aren't readable. I would argue that this lib is so small and simple, there could easily be two separate versions—one for es5 and one for es6—that wouldn't require too much effort. And, we would get the added bonus of clean, human-readable code.

**Comment by framespaces-dev** [comment]
Thanks Kevin!
Please could you re-publish to npm?

**Comment by framespaces-dev** [comment]
Re TypeScript: I suggest that this library is (marvellously) clean and human-readable already. Using the basic lowest-common-denominator means the lowest barriers to usage and the lowest maintenance cost. I think the advantages of TypeScript for team-working and management of complexity are not very applicable here.
Unless you really want to try it out and learn about it of course!
Just my 2c; best regards, George

**Comment by thelonious** [comment]
@framespaces-dev Well said and I agree.

I've pushed version 2.0.0 to npm. I had to bump the major revision number because there is a breaking API change. I have not updated any other modules that use this affine lib. I need to check that the API change doesn't break those.

**Pull request merged**
